/tamt/costmap_module:
  ros__parameters:
    #! Camera parameters
    camera:
      tilt_angle: 20.0  # Camera tilt angle from horizontal (degrees)
      fov_x: 110.0  # Field of view in X direction (degrees) Horizontal
      fov_y: 70.0  # Field of view in Y direction (degrees) Vertical
      max_distance: 2.5  # Maximum sensing distance (meters)
      height: 0.43  # Camera height from ground (meters)
      
      resolution:
        width: 960  # Camera image width (pixels)
        height: 540  # Camera image height (pixels)

      intrinsics:
        fx: 685.51  # Focal length in pixels (x-axis)
        fy: 189.06  # Focal length in pixels (y-axis)
        cx: 480.00  # Principal point x-coordinate in pixels
        cy: 270.00  # Principal point y-coordinate in pixels

      # Static transform from rover frame to camera frame
      transform:
        translation:
          x: 0.157499
          y: 0.059899
          z: 0.238857
        rotation: # quat that rotates from rover frame to camera frame (horizontal)
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5
    
    #! Rover parameters
    rover:
      width: 1.0  # Rover width (meters)
      length: 1.2  # Rover length (meters)
    
    #! Costmap parameters
    costmap:
      publish_individual_layers: true
      publish_visualizations: true
      internal_resolution: 0.01  # Internal costmap resolution (meters per cell)
      output_resolution: 0.05  # Costmap resolution (meters per cell)

      # Costmap weights should sum to 1
      weight_sne: 0.4  # Weight for SNE costmap
      weight_segmentation: 0.3  # Weight for segmentation costmap
      weight_roughness: 0.3  # Weight for roughness costmap
      
      segmentation:
        dilation_enabled: true
        dilation_kernel_size: 3
        dilation_min_confidence: 0.7
        
    
    #! Class risk parameters
    class_risks:
      soil: 0.2
      bedrock: 0.1
      sand: 0.3
      rocks: 0.9
      hole: 1.0