/tamt/**:
  ros__parameters:
    #! Camera parameters
    synchronization:
      timeout_sec: 20.0  # Time to wait before giving error 

    camera:
      tilt_angle: 20.0  # Camera tilt angle from horizontal (degrees)
      fov_x: 110.0  # Field of view in X direction (degrees) Horizontal
      fov_y: 70.0  # Field of view in Y direction (degrees) Vertical
      max_distance: 3.0  # Maximum sensing distance (meters)
      height: 0.43  # Camera height from ground (meters)
      
      resolution:
        width: 960  # Camera image width (pixels)
        height: 540  # Camera image height (pixels)

      intrinsics:
        fx: 336.1  # Focal length in pixels (x-axis)
        fy: 385.6  # Focal length in pixels (y-axis)
        cx: 480.0 # Principal point x-coordinate in pixels
        cy: 270.0  # Principal point y-coordinate in pixels

      # Static transform from rover frame to camera frame
      transform:
        translation:
          x: 0.157499
          y: 0.059899
          z: 0.238857
        rotation: # quat that rotates from rover frame to camera frame (horizontal)
          x: 0.5
          y: -0.5
          z: -0.5
          w: 0.5
    
    #! Segmentation parameters
    segmentation:
      model:
        model_dir: 'models/TAMT.pt' # Relative to workspace root "/home/spacerob/tamt/src/terrain_segmentation/models/TAMT.pt"
        device: '0'  # Device to use: 0, 1, 2, etc., 'cpu'
      
      inference:
        conf: 0.25          # Confidence threshold
        iou: 0.50           # IoU threshold for NMS
        imgsz: 640          # Input image size
        max_det: 300        # Maximum number of detections per image
    
    #! Costmap parameters
    costmap:
      auto_fetch_enabled: true  # Enable automatic fetching of sensor data
      publish_individual_layers: true
      publish_visualizations: true
      internal_resolution: 0.01  # Internal costmap resolution (meters per cell)
      output_resolution: 0.02  # Costmap resolution (meters per cell)
     
      segmentation_costmap:
        dilation_enabled: false # Enable dilation of segmentation costmap
        dilation_kernel_size: 3 # Kernel size for dilation (odd integer)
        dilation_min_confidence: 0.7 # Minimum confidence to consider for dilation (0.0-1.0)
        confidence_dampening: 0.75  # Dampening factor for confidence influence on cost (0.0-1.0)

      roughness_costmap:
        dilation_enabled: true # Enable dilation of roughness costmap
        dilation_iterations: 2 # Number of dilation iterations

      # Costmap weights should sum to 1
      combined_costmap:
        weights:
          sne: 0.2 # Weight for SNE costmap
          segmentation: 0.6  # Weight for segmentation costmap
          roughness: 0.2  # Weight for roughness costmap
          
    
    #! Class risk parameters
    class_risks: # Risk values for each terrain class (0.0 = no risk, 1.0 = maximum risk)
      soil: 0.2
      bedrock: 0.1
      sand: 0.3
      rocks: 0.9
      hole: 1.0
